    # This file contains variables that are common across all hosts in the Ansible inventory.

    # --- Common Packages ---
    # List of common packages that have the same name across OS families.
    # OS-specific packages will be defined in OS-specific group_vars files.
    common_packages:
      - curl
      - wget
      - tar
      - gzip
    # iptables-services, ufw, and gnupg are OS-specific and will be defined in
    # inventory/group_vars/centos_servers.yml and inventory/group_vars/ubuntu_servers.yml

    # --- Node Exporter Variables ---
    # Default port for Node Exporter
    node_exporter_port: 9100

    # Default version for Node Exporter (check the latest stable release on GitHub)
    # Find releases here: https://github.com/prometheus/node_exporter/releases
    node_exporter_version: "1.8.1" # <-- Check for the latest stable version

    # Base URL for downloading Node Exporter (constructed in role tasks)
    # node_exporter_download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"

    # User and group for the node_exporter process
    node_exporter_user: "node_exporter"
    node_exporter_group: "node_exporter"
    node_exporter_install_dir: "/usr/local/bin"
    # Shell path for the node_exporter user (defined conditionally in common role)
    # node_exporter_shell: "/usr/sbin/nologin" # Or /bin/false depending on OS

    # Installation directory for the node_exporter binary (used in role tasks)
    # node_exporter_install_dir: "/usr/local/bin"

    # Web listen address and port for Node Exporter (used in service file and firewall)
    node_exporter_web_listen_address: "0.0.0.0:9100" # Listen on all interfaces on port 9100
    node_exporter_web_listen_port: 9100 # Just the port number for firewall rules

    # Node Exporter checksum (fetched dynamically in role tasks)
    # node_exporter_checksum: "sha256:..."

    # --- Prometheus Variables ---
    prometheus_version: "2.50.1" # <-- Check for the latest stable release on GitHub
    # Find releases here: https://github.com/prometheus/prometheus/releases
    # Prometheus download URL (constructed in role tasks)
    prometheus_download_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"

    # User and group for the prometheus process
    prometheus_user: "prometheus" # Often different from node_exporter user
    prometheus_group: "prometheus" # Often different from node_exporter group
    prometheus_shell: "/usr/sbin/nologin" # Standard nologin shell path

    # Path where the prometheus and promtool binaries will be installed
    prometheus_binary_install_dir: "/usr/local/bin"

    # Directory for Prometheus configuration and data
    prometheus_config_dir: "/etc/prometheus"
    prometheus_data_dir: "/var/lib/prometheus"

    # Default port for Prometheus server HTTP interface
    prometheus_web_port: 9090

    # Default port for Prometheus pushgateway (not used in this playbook, but common var)
    # prometheus_pushgateway_port: 9091

    # Default scrape interval for jobs
    prometheus_global_scrape_interval: "15s"

    # List of scrape jobs (This will define what Prometheus monitors)
    # We will add our node_exporter targets here later
    prometheus_scrape_jobs: [] # Start with an empty list

    # --- Grafana Variables ---
    grafana_web_port: 3000 # Default port for Grafana web interface

    # Grafana installation details (repository specifics will go in OS group_vars)
    # Corrected variables for Ubuntu APT repo
    grafana_apt_repo_baseurl: "https://apt.grafana.com/" # <-- Base URL
    grafana_apt_repo_release: "stable" # <-- Grafana release type (stable, beta)
    grafana_apt_repo_components: "main" # <-- Usually 'main'
    grafana_repo_gpgkey_ubuntu: "https://apt.grafana.com/gpg.key" # GPG key URL

    # CentOS/RHEL RPM repo details (baseurl seems correct, keep it)
    grafana_rpm_repo_baseurl: "https://rpm.grafana.com/oss/rpm" # CentOS/RHEL repo URL
    grafana_repo_gpgkey_centos: "https://rpm.grafana.com/gpg.key" # CentOS/RHEL GPG key URL.
    