
pkg_manager: "apt"
common_packages:
  - curl
  - wget
  - tar
  - gzip
  - ufw

# Node Exporter service name on Ubuntu
node_exporter_service_name: "node_exporter"

# Directory for systemd service files
systemd_service_dir: "/etc/systemd/system"

# User and group for the node_exporter process
node_exporter_user: "node_exporter"
node_exporter_group: "node_exporter"

# Shell for the node_exporter user
node_exporter_shell: "/usr/sbin/nologin" # Different path on Ubuntu

# Path where the node_exporter binary will be installed
node_exporter_install_dir: "/usr/local/bin"

# Firewall command for Ubuntu (using ufw)
firewall_cmd: "ufw"

# Grafana Repository Configuration for Ubuntu/Debian (uses variables from all.yml and this file)
grafana_repo: # This structure is used by apt_repository
  repo: "deb [signed-by=/usr/share/keyrings/grafana.gpg] {{ grafana_apt_repo_baseurl }} {{ grafana_apt_repo_release }} {{ grafana_apt_repo_components }}"
  state: present
  filename: grafana # Name of the repo file in /etc/apt/sources.list.d/
  update_cache: yes # Update apt cache after adding repo