# This playbook deploys monitoring agents and servers using Ansible roles.
# It includes tasks for installing and configuring Node Exporter, Prometheus, and Grafana.

- name: Deploy Monitoring Agents (Node Exporter)
  hosts: monitoring_agents # <-- This play targets the agents
  become: yes
  gather_facts: yes

  roles:
    - role: common
    - role: node_exporter

- name: Deploy Prometheus and Grafana Servers
  hosts: monitoring_servers # <-- This play targets the monitoring servers
  become: yes
  gather_facts: yes

  # Keep the vars section to ensure variables like firewall_cmd are defined
  vars:
    firewall_cmd: >-
      {% if ansible_os_family == 'RedHat' %}
      "firewall-cmd"
      {% elif ansible_os_family == 'Debian' %}
      "ufw"
      {% else %}
      "unknown_firewall"
      {% endif %}

  roles:
    - role: prometheus # <-- Include the prometheus role
    - role: grafana # <-- Include the grafana role