- name: Deploy the Monitoring Stack
  hosts: monitoring_agents # <-- Target the group containing all 6 servers (CentOS and Ubuntu)
  become: yes # <-- Run tasks with elevated privileges (sudo)
  gather_facts: yes # <-- Gather facts about the target hosts (OS, distribution, etc.)

  roles:
    - role: common
    - role: node_exporter

- name: Deploy Monitoring Agents (Node Exporter)
  hosts: monitoring_agents # <-- This play targets the agents
  become: yes
  gather_facts: yes

  roles:
    - role: common
    - role: node_exporter

- name: Deploy Prometheus Server
  hosts: monitoring_servers
  become: yes
  gather_facts: yes

  vars: 
    firewall_cmd: >- # Define firewall_cmd conditionally
      {% if ansible_os_family == 'RedHat' %}
      "firewall-cmd" # Value for RedHat
      {% elif ansible_os_family == 'Debian' %}
      "ufw" # Value for Debian
      {% else %}
      "unknown_firewall" # Default value for other OS families
      {% endif %}# Explicitly load ubuntu_servers.yml

  roles:
    - role: prometheus